"""Resolve, discover and strip a content directory (1.1-1.8, 2.11).

Nothing here writes: files are only ever read, and the directory walk only
lists. Frontmatter validation is added to this module by a later task.
"""

from __future__ import annotations

import os
from collections.abc import Mapping
from dataclasses import dataclass
from pathlib import Path

from scripts.sitebuild.model import (
    ANNOTATION_MARKER,
    CONTENT_ENV_VAR,
    RESERVED_ROOT_NAMES,
    Asset,
    ContentSource,
    Problem,
    ResolvedContent,
)


class ContentDirMissing(Exception):
    """The resolved content directory is not an existing directory (1.2)."""

    def __init__(self, resolved: ResolvedContent) -> None:
        self.resolved = resolved
        super().__init__(
            f"content directory {resolved.path} does not exist or is not a "
            f"directory (resolved from {resolved.source.value})"
        )


@dataclass(frozen=True)
class Discovery:
    """What the walk found; every sequence is sorted by content-relative path."""

    pages: tuple[str, ...]  # `.md` candidates, before frontmatter validation
    assets: tuple[Asset, ...]
    problems: tuple[Problem, ...]


def resolve_content_dir(
    option: Path | None, environ: Mapping[str, str], repo_root: Path
) -> ResolvedContent:
    """Pick the content directory: option, then environment, then the default (1.1).

    The first source that is set wins, and it must exist (1.2): a missing
    directory raises `ContentDirMissing` rather than falling to the next source.
    """
    resolved: ResolvedContent
    if option is not None:
        resolved = ResolvedContent(option, ContentSource.OPTION)
    elif environ.get(CONTENT_ENV_VAR):
        resolved = ResolvedContent(
            Path(environ[CONTENT_ENV_VAR]), ContentSource.ENVIRONMENT
        )
    else:
        resolved = ResolvedContent(
            repo_root / "website" / "content", ContentSource.DEFAULT
        )
    if not resolved.path.is_dir():
        raise ContentDirMissing(resolved)
    return resolved


def discover(content_dir: Path) -> Discovery:
    """Walk ``content_dir`` with `os.scandir`, never following a symbolic link.

    A symbolic link anywhere is a problem, including under a name that begins
    with ``_`` or ``.`` and inside an excluded directory (2.11). Names beginning
    with ``_`` or ``.`` are excluded with their subtrees (1.4): those
    directories are still walked, for symbolic links only, and nothing beneath
    them becomes a page or an asset. A reserved name at the root, of any entry
    type, is a problem; a reserved directory is walked as excluded, for symbolic
    links only (2.11). An excluded directory that cannot be listed is skipped,
    since it contributes nothing to the site. An unreadable included directory
    is an error, surfaced for now as the `OSError` (its exact handling is
    queued as docs-site-unreadable-dirs-and-special-files-in-content in
    .kiro/queue/). A ``.md`` file is a page candidate; any other file is an
    asset (1.5).
    """
    pages: list[str] = []
    assets: list[Asset] = []
    problems: list[Problem] = []
    pending: list[tuple[Path, str, bool]] = [(content_dir, "", False)]
    while pending:
        directory, prefix, inside_excluded = pending.pop()
        try:
            with os.scandir(directory) as entries:
                listing = sorted(entries, key=lambda entry: entry.name)
        except OSError:
            if inside_excluded:
                continue
            raise
        for entry in listing:
            rel = prefix + entry.name
            if entry.is_symlink():
                problems.append(Problem(rel, "", "symbolic link is not allowed"))
                continue
            excluded = inside_excluded or entry.name.startswith(("_", "."))
            if not prefix and entry.name in RESERVED_ROOT_NAMES:
                problems.append(
                    Problem(rel, "", "reserved name, generated by the build")
                )
                if entry.is_dir(follow_symlinks=False):
                    pending.append((Path(entry.path), rel + "/", True))
            elif entry.is_dir(follow_symlinks=False):
                pending.append((Path(entry.path), rel + "/", excluded))
            elif excluded:
                continue
            elif entry.name.endswith(".md"):
                pages.append(rel)
            else:
                assets.append(Asset(rel, Path(entry.path)))
    return Discovery(
        pages=tuple(sorted(pages)),
        assets=tuple(sorted(assets, key=lambda asset: asset.path)),
        problems=tuple(sorted(problems, key=lambda p: (p.path, p.where, p.message))),
    )


def strip_annotation(text: str) -> str:
    """Remove a trailing annotation block, keeping everything else exactly (1.6-1.8).

    The block starts at the last blank line followed by ``---`` and a line
    beginning ``Annotations:``. The kept text ends with the newline that closed
    the last content line. Without a marker the text is returned unchanged.
    """
    i = text.rfind(ANNOTATION_MARKER)
    if i < 0:
        return text
    return text[: i + 1]
